### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by boranityy** [SpotX-CLI/SpotX-Linux#24]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

turkey

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.1.84.716
- Distro: Arch Linux
- Shell: Zsh
```

### 📝 Description

Not working Adblock and Old UI. was working before

### 🖵 Terminal Output

boranity in ~ λ bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Linux/main/install.sh) -o

**************************
SpotX-Linux by @SpotX-CLI
**************************

SpotX-Linux version: 1.2.1.968-1

Spotify directory found in PATH: /opt/spotify
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)

Spotify version:  1.1.84.716

SpotX backup found, SpotX has already been used on this install.
Re-run SpotX using the '-f' flag to force xpui patching.

Skipping xpui patches and continuing SpotX...
Applying SpotX patches...
SpotX finished patching!

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/107348321/209708788-cc848423-fea7-4186-9b70-4b0b52b8e860.png)

**Comment by jetfir3** [comment]
In your example terminal output it shows that SpotX was already installed and did not attempt to re-patch anything because the `-f` flag was not used. 

There's no reason to use the `-o` flag if using v1.1.84.x as the new UI isn't possible until v1.1.93.896.

You also mention that it was working before, so something has changed since then.. try to figure out what changed.
The issue is possibly due to Spicetify but hard to say.

I would suggest uninstalling Spotify completely, reinstall Spotify then run SpotX-Linux and test (before using Spicetify).
